config/routes.rb
Rails.application.routes.draw do
  get 'web/home'
  get 'about-us', to: 'web#about_us'
  post 'web/search'

  root to: 'web#home'

  resources :books, except: [:new, :create]
  resources :authors do
    resources :books
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :reviews, as: :reviewable
  has_many :books
  validates :email, :first_name, presence: true

  REDIRECTED_AUTHORS = { '122' => 132, '125' => 135 }

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, as: :reviewable
  belongs_to :author, counter_cache: true
  validates :author, presence: { if: :new_data? }

  delegate :first_name, to: :author, prefix: true

  scope :with_title, -> { where.not(title: nil) }
  scope :from_year, ->(year) { where('created_at > ?', Date.new(year)) }

  attr_accessor :price

  VAT_BOOK = 4

  def price_vat_included
    return 0 if price.nil?
    vat = price * VAT_BOOK / 100
    total_price = price + vat
  end

  def reviews_count
    reviews.count
  end

  private

  def new_data?
    created_at.nil? || created_at > Date.new(2019)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_variant
  before_action :set_locale
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  def render_404
    render 'web/404', status: 404
  end

  def set_variant
    request.variant =
    if browser.device.tablet?
      :tablet
    elsif browser.device.mobile?
      :phone
    else
      :desktop
    end
  end

  def set_locale
    I18n.locale = params[:locale] if params.include?(:locale)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :redirected_authors, only: :show
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.order(params_order_to_db)
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def params_order_to_db
    {
      name: :first_name,
      created_at: 'created_at DESC'
    }[params[:order]].&:to_sym || :email
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    def redirected_authors
      return unless params[:id].in? Author::REDIRECTED_AUTHORS.keys
      redirect_to author_path(Author::REDIRECTED_AUTHORS[params[:id]])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :email, :phone, :city, :address, :website)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(author_id: params[:author_id]).presence || Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @author = Author.find(params[:author_id])
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.author_id = params[:author_id]

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id, :description, :year, :available, :section, :shelf, :order)
    end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  def home
    version = request.variant[0].to_s
    @title = (t 'h1.home') << version
  end

  def about_us
  end

  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg
  - %i(first_name last_name email phone city address website).each do |field|
    = render '/common/field_text', f: f, field: field
  .actions
    = f.submit 'Save'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
- content_for :presearch_tip do
  %p tip: search by author

%h1 Listing authors

%table
  %thead
    %tr
      - author_atributos = %w[first_name last_name email phone city address website]

      - author_atributos.each do |atributo|
        %th
          = (t "activerecord.models.attributes.#{atributo}").capitalize
      %th
      %th
      %th

  %tbody
    - @authors.each do |author|
      %tr
        %td= author.first_name
        %td= author.last_name
        %td= author.email
        %td= author.phone
        %td= author.city
        %td= author.address
        %td= author.website
        %td= link_to 'Show', author
        %td= link_to 'Edit', edit_author_path(author)
        %td= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @author.first_name
%p
  %b Last name:
  = @author.last_name
%p
  %b Email:
  = @author.email
%p
  %b Phone:
  = @author.phone
%p
  %b City:
  = @author.city
%p
  %b Address:
  = @author.address
%p
  %b Website:
  = @author.website
%p
  = link_to 'See books!!', author_books_path(@author)
  = link_to 'New Book', new_author_book_path(@author)

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path

app/views/books/_form.html.haml
= form_for [@author, @book] do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :author
    = f.collection_select :author_id, Author.all, :id, :last_name, include_blank: true
  = render '/common/field_text', f: f, field: :title
  = render '/common/field_text', f: f, field: :description
  = render '/common/field_text', f: f, field: :section
  = render '/common/field_number', f: f, field: :year
  = render '/common/field_number', f: f, field: :shelf
  = render '/common/field_number', f: f, field: :order
  .field
    = f.label :available
    = f.check_box :available
  .actions
    = f.submit 'Save'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
- content_for(:title) do
  Book list
%h1
  = t 'h1.books'

%table
  %thead
    %tr
    - book_atributos = %w[title author description year available section shelf order]

    - book_atributos.each do |atributo|
      %th
        = (t "activerecord.models.attributes.#{atributo}").capitalize

    %th
    %th
    %th

  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.author
        %td= book.description
        %td= book.year
        %td= book.available
        %td= book.section
        %td= book.shelf
        %td= book.order
        %td= link_to (t 'actions.show'), book_path(book)
        %td= link_to (t 'actions.edit'), edit_book_path(book)
        %td= link_to (t 'actions.destroy'), book, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %br

app/views/books/new.html.haml
%h1 Creating new book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title
%p
  %b Author:
  = link_to @book.author, author_path(@book.author_id)
%p
  %b Description:
  = @book.description
%p
  %b Year:
  = @book.year
%p
  %b Available:
  = @book.available
%p
  %b Section:
  = @book.section
%p
  %b Shelf:
  = @book.shelf
%p
  %b Order:
  = @book.order

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/common/_field_number.html.haml
.field
  = f.label field
  = f.number_field field

app/views/common/_field_text.html.haml
.field
  = f.label field
  = f.text_field field

app/views/layouts/application.en_GB.html.haml
!!!
%html
  %head
    %title
      = yield(:title).presence || 'Biblioteca, your best pet project'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %ul
      %li= link_to (t 'activerecord.models.author.other'), authors_path
      %li= link_to (t 'activerecord.models.books.other'), books_path
      %li= link_to (t 'actions.home'), web_home_path
      %li= link_to (t 'actions.about_us'), about_us_path
    = yield(:presearch_tip)
    %p
      = form_tag web_search_path do
        = text_field_tag :text_to_search
        = submit_tag
  = yield

%p
  %locale: #{I18n.locale}
  = I18n.localize Time.current, format: :short
- console if Rails.env.development?

app/views/layouts/application.es_ES.html.haml
!!!
%html
  %head
    %title
      = yield(:title).presence || 'Biblioteca, your best pet project'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %ul
      %li= link_to (t 'activerecord.models.author.other'), authors_path
      %li= link_to (t 'activerecord.models.books.other'), books_path
      %li= link_to (t 'actions.home'), web_home_path
      %li= link_to (t 'actions.about_us'), about_us_path
    = yield(:presearch_tip)
    %p
      = form_tag web_search_path do
        = text_field_tag :text_to_search
        = submit_tag
  = yield

%p
  %locale: #{I18n.locale}
  = I18n.localize Time.current, format: :long
- console if Rails.env.development?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title).presence || 'Biblioteca, your best pet project'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %ul
      %li= link_to (t 'activerecord.models.author.other'), authors_path
      %li= link_to (t 'activerecord.models.book.other'), books_path
      %li= link_to (t 'actions.home'), web_home_path
      %li= link_to (t 'actions.about_us'), about_us_path
    = yield(:presearch_tip)
    %p
      = form_tag web_search_path do
        = text_field_tag :text_to_search
        = submit_tag
  = yield
  %p
    locale: #{I18n.locale}
    = I18n.localize Time.current, format: :long
  %p
    = link_to 'Español', request.path.to_s + '?locale=es'
    = link_to 'Inglés', request.path.to_s + '?locale=en'
  - console if Rails.env.development?

app/views/web/404.html.haml
%h1
  Ooops! La página que buscas no existe

%p Prueba nuestro buscador o comprueba tus datos

app/views/web/about_us.html.haml
%h1
  = t 'h1.about_us'
%p Find me in app/views/web/about_us.html.haml

app/views/web/home.html+phone.haml
%h1
  Biblioteca home page for
  phone
Current variant: #{request.variant}

app/views/web/home.html+tablet.haml
%h1
  Biblioteca home page for
  tablet
Current variant: #{request.variant}

app/views/web/home.html.haml
%h1
  = @title
Current variant: #{request.variant}

app/views/web/search.html.haml
%h1 Web#search
%p Searching for #{params[:text_to_search]}